name: Chrome Extension CI

on:
  push:
    branches: [ main ]
    paths: 
      - 'extension/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'extension/**'

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # Navigate to the extension directory
    - name: Change to Extension Directory
      run: cd extension
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    # Run npm commands in the extension directory
    - name: Install Dependencies
      run: |
        cd extension
        npm install
    
    - name: pack Extension
      uses: TheDoctor0/zip-release@0.7.6
      with: 
        filename: ./package.zip
        exclusions: '.git/* .vscode/* .github/* *.md'
            
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: extension-package
        path: ./package.zip
